baseurl = "http://www.jprocha.me"
title = "jprocha"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
enableEmoji = true

[pagination]
pagerSize = 20

[services]

# [services.disqus]
# shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "João Pedro Rocha"
  info = "Scientific {Computing, Machine Learning}"
  description = "João's personal page"
  keywords = "blog,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2025

  enableTwemoji = true


  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/jpssrocha/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/joao-pedro-rocha-b28b7b219/"

[[params.social]]
  name = "RSS"
  icon = "fa-solid fa-rss fa-2x"
  weight = 3
  url = "https://myhugosite.com/index.xml"
  rel = "alternate"
  type = "application/rss+xml"


# Menu links

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "TIL"
weight = 4
url = "til/"

[languages.pt-br]
languageName = ":brazil:"

[languages.pt-br.params]
info = "{Computação, Aprendizagem de Máquina} Científic@"
description = "Página pessoal do João"
keywords = "blog,pessoal"

[[languages.pt-br.menu.main]]
name = "Sobre"
weight = 1
url = "about/"

[[languages.pt-br.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.pt-br.menu.main]]
name = "Projetos"
weight = 3
url = "projects/"

[[languages.pt-br.menu.main]]
name = "TIL"
weight = 4
url = "til/"
